import type { Metadata } from "next";
import "./globals.css";
import { chakraPetch, jetBrains } from "./fonts";
import Navbar from "./components/layout/Navbar";
import Footer from "./components/layout/Footer";

export const metadata: Metadata = {
  title: "Tech Conference App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${jetBrains.variable} ${chakraPetch.variable} h-full antialiased`}
    >
      <body id="top" className="min-h-full flex flex-col">
        <div className="mx-4 min-[1300px]:mx-10 overflow-hidden">
          <Navbar />
          {children}
          <Footer />
        </div>
      </body>
    </html>
  );
}
