import type { Metadata } from "next";
import "./globals.css";
import { chakraPetch, jetBrains } from "./fonts";

export const metadata: Metadata = {
  title: "Tech Conference App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${jetBrains.variable} ${chakraPetch.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">{children}</body>
    </html>
  );
}
